### ISSUE TITLE
会出现同样的牌

### ISSUE THREAD

**Issue by rushairer** [rrylee/phppoker#1]
比如 

+----------+-----------------+
| Username | Hand            |
+----------+-----------------+
| 你       | 3♠ 4♣ 3♠ 6♥ 3♣  |
| 我       | 7♣ 4♣ 3♠ 6♠ Q♠  |
| 他       | 10♥ J♥ J♥ 6♠ 2♠ |
+----------+-----------------+

3♠   J♥ 就重复多次出现了

**Comment by sword-jin** [comment]
👍  回忆了下，当时好像确实没有考虑多人用的是同一副牌的情况

**Comment by AlanLongYu** [comment]
![image](https://user-images.githubusercontent.com/6948952/40816164-e5947944-657d-11e8-9371-9d80050e6a3e.png)
确实会出同样的牌第二个人有两个红桃J，没有尝试去修复么，还有在PHP7.1版本会报错Warning: A non-numeric value encountered in phppoker\src\Kernel\Poke
r.php on line 125

**Comment by sword-jin** [comment]
@AlanLongYu fixed
重复牌要加个唯一

**Comment by sword-jin** [comment]
https://github.com/rrylee/phppoker/releases/tag/v1.0.1
